### ISSUE TITLE
ERROR: Tmuxifier requires Tmux v1.6 or newer. You have vnext-3.4.

### ISSUE THREAD

**Issue by joaopedroaat** [jimeh/tmuxifier#94]
I'm getting this error using tmux installed with dnf on Fedora 39

`tmuxifier

~/.tmux/plugins/tmuxifier/libexec/tmuxifier-tmux-version: line 35: ((: 10#: invalid integer constant (error token is "10#")
~/.tmux/plugins/tmuxifier/libexec/tmuxifier-tmux-version: line 37: ((: 10#: invalid integer constant (error token is "10#")
ERROR: Tmuxifier requires Tmux v1.6 or newer. You have vnext-3.4.`

`tmux -V

tmux next-3.4
`

**Comment by maxisusi** [comment]
The issue comes from a regex inside `tmuxifier-tmux-version`  ([here](https://github.com/jimeh/tmuxifier/blob/fe1f6c473477dd9aba37458fedd3b704c9288d3c/libexec/tmuxifier-tmux-version#L59C7-L59C7)) where it removes alphabetic characters. Unfortunally, `vnext-3.4` with keep the hypen-minus "-". resulting in an invalid version `-3.4`. 

The workaround is to just add a hypen-minus on the regex to escale it.  `version=${version//+([a-zA-Z-])/}`

**Comment by joaopedroaat** [comment]
I made a pull request with the fix. Waiting for it to be approved. Thanks!

**Comment by maxisusi** [comment]
#95
